language: R

cache: packages

r:
 - release
 - devel

sudo: required

before install:
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 - sudo apt-get update -qq
 - sudo aptitude install -y gdal-bin
 - sudo aptitude install -y libgdal1-dev
 - sudo aptitude install -y libproj-dev
 - sudo apt-get install libudunits2-dev
 - sudo apt-get install libssh2-1-dev
 - sudo apt-get install netcdf-bin

r_github_packages:
 - r-lib/covr

script:
 - R CMD build .
 - R CMD check *tar.gz


after_success:
 - Rscript -e 'library(covr); codecov()'