language: R

cache: packages

r:
 - release
 - devel

sudo: required

before install:
 - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_github_packages:
- r-lib/covr

script:
 - R CMD build .
 - R CMD check *tar.gz


after_success:
 - Rscript -e 'library(covr); codecov()'