language: R

r:
 - release
 - devel

sudo: required

before install:
 - sudo apt-get install libudunits2-dev
 - R -e 'install.packages("devtools")'
 - R -e 'install.packages("covr")'
 
r_github_packages:
- r-lib/covr

after_success:
 - Rscript -e 'library(covr); codecov()'