language: R

cache: packages

r:
 - release
 - devel

sudo: required

before install:
 - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
 
r_github_packages:
- r-lib/covr

install:
  - R -e 'devtools::install_deps(dep = T)'

after_success:
 - Rscript -e 'library(covr); codecov()'