# A script for linking the relevant outputs generated by the MySQL table to the folder structure for each database

source("R/Essentials.R")

Stab<-dbGetQuery(con,statement=paste("show tables like '%test_%'")) %>% unlist(use.names = F)
Stab.replace<- map(test.tabs$Table,function(x) str_replace(x,"_inv",""))

# Create the Real names and Type of Table
.tableclass<-function(x){
  
  y1<-str_replace(x,"_inv","")
  y2<-str_split(y1,"_") %>% unlist
  y3<-c(paste(y2[1],y2[2],sep = "_"),y2[3])
  return(y3)
}

# Collect all the Information from the Tables according to the Test prefix
cost.tabs.all<-map(Stab,function(x){
  
  cnt  <- dbGetQuery(con,statement=paste("select count(*) from",x))[[1]] %>% as.numeric
  read <- dbGetQuery(con,statement=paste0("select * from information_schema.columns where table_name='",x,"' and column_name like 'id%'")) %>% as.tibble
  r1   <- read %>% 
    filter(TABLE_SCHEMA==database) %>% 
    select(Database=TABLE_SCHEMA,Table=TABLE_NAME,IDs=COLUMN_NAME)
  r1$Count<-cnt
  
  r1$Table_Type<-map_chr(r1$Table,function(x) .tableclass(x)[1])
  r1$Table_Name<-map_chr(r1$Table,function(x) .tableclass(x)[2])
  
  return(r1)
  
}) %>% do.call(rbind,.)


# Sort the Table
cost.tabs.arr <- cost.tabs.all %>% arrange(Table_Type,IDs) 
cost.tabs.from<- cost.tabs.arr %>% filter(grepl("ID_T",IDs)) %>% mutate(ID_from=IDs) %>% select(-IDs)
cost.tabs.to  <- cost.tabs.arr %>% filter(grepl("id_t",IDs)) %>% mutate(ID_to=IDs) %>% select(-IDs)
cost.tabs     <- left_join(cost.tabs.from,cost.tabs.to) %>% filter(Count>0)

# First Table
cf1.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[1])) %>% as.tibble
cf1<-cf1.read %>% 
  mutate(Info=map(cf1<-general_info,function(x){
    
    matall<-readMat(x)$data[,,1]
    matall.rtm<-matall$rtm[,,1] %>% 
      melt %>% 
      select(Type=L1,Value=value)
    
  })) %>% select(-general_info)

# Second Table

.sqljoin<-function(tableto,tablefrom){
  
  colnames(tablefrom)<-toupper(colnames(tablefrom))
  tojoin<-colnames(tablefrom)[2]
  ret<-left_join(tableto,tablefrom,by=tojoin)
  return(ret)
  
}


for(i in 1:nrow(cf1)){
  
  cf11<-cf1[i,]
  
  lines<-str_detect(cost.tabs$ID_to,"id_t[:digit:]") %>% which
  cost.tabs.used<-cost.tabs %>% slice(lines)
  
  for(j in 1:nrow(cost.tabs.used)){
    
    if(j==1) to<-cf11
    is<-cost.tabs.used[j,]
    
    cf2.read<-dbGetQuery(con,statement=paste("select * from",is$Table,"where",is$ID_to,"=",to$ID_T1)) %>% as.tibble
    to<-.sqljoin(to,cf2.read)
    
    
  }
  map(cost.tabs.used$Table,function(x){
    
    cf2.read<-dbGetQuery(con,statement=paste("select * from",x,"where")) %>% as.tibble
    print(cf11[1,])
    cf11<-.sqljoin(cf11,cf2.read)
    print(cf11[1,])
    
    
  })
  
}


cf2.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[2])) %>% as.tibble
cf2<-.sqljoin(cf1,cf2.read)
cf3.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[3])) %>% as.tibble
cf3<-.sqljoin(cf2,cf3.read)
cf4.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[4])) %>% as.tibble
cf4<-.sqljoin(cf3,cf4.read)
cf5.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[5])) %>% as.tibble
cf5<-.sqljoin(cf4,cf5.read)
cf6.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[6])) %>% as.tibble
cf6<-.sqljoin(cf5,cf6.read)
cf7.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[7])) %>% as.tibble
cf7<-.sqljoin(cf6,cf7.read)
cf8.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[8])) %>% as.tibble
cf8<-.sqljoin(cf7,cf8.read)

