# A script for linking the relevant outputs generated by the MySQL table to the folder structure for each database

source("R/Essentials.R")

outdir<-"C:/ARTMO/"

Stab<-dbGetQuery(con,statement=paste("show tables like '%test_%'")) %>% unlist(use.names = F)
Stab.replace<- map(Stab,function(x) str_replace(x,"_inv",""))

# Create the Real names and Type of Table
.tableclass<-function(x){
  
  y1<-str_replace(x,"_inv","")
  y2<-str_split(y1,"_") %>% unlist
  y3<-c(paste(y2[1],y2[2],sep = "_"),y2[3])
  return(y3)
}

# Collect all the Information from the Tables according to the Test prefix
cost.tabs.all<-map(Stab,function(x){
  
  cnt  <- dbGetQuery(con,statement=paste("select count(*) from",x))[[1]] %>% as.numeric
  read <- dbGetQuery(con,statement=paste0("select * from information_schema.columns where table_name='",x,"' and column_name like 'id%'")) %>% as.tibble
  r1   <- read %>% 
    filter(TABLE_SCHEMA==database) %>% 
    select(Database=TABLE_SCHEMA,Table=TABLE_NAME,IDs=COLUMN_NAME)
  r1$Count<-cnt
  
  r1$Table_Type<-map_chr(r1$Table,function(x) .tableclass(x)[1])
  r1$Table_Name<-map_chr(r1$Table,function(x) .tableclass(x)[2])
  
  return(r1)
  
}) %>% do.call(rbind,.)


# Sort the Table
cost.tabs.arr <- cost.tabs.all %>% arrange(Table_Type,IDs) 
cost.tabs.from<- cost.tabs.arr %>% filter(grepl("ID_T",IDs)) %>% mutate(ID_from=IDs) %>% select(-IDs)
cost.tabs.to  <- cost.tabs.arr %>% filter(grepl("id_t",IDs)) %>% mutate(ID_to=IDs) %>% select(-IDs)
cost.tabs     <- left_join(cost.tabs.from,cost.tabs.to) %>% filter(Count>0)

# First Table
cf1.read<-dbGetQuery(con,statement=paste("select * from",cost.tabs$Table[1])) %>% as.tibble

meta<-map_df(cf1.read$general_info,function(x){
  
  matall<-readMat(x)$data[,,1]
  matall.rtm<-matall$rtm[,,1] %>% 
    melt %>% 
    select(Type=L1,Value=value) %>% 
    filter(Type!="rtm") %>% t %>% as.tibble
  colnames(matall.rtm)<-matall.rtm[1,]
  matall.rtm<-matall.rtm %>% dplyr::select(database,project,id,date)
  matall.rtm<-matall.rtm[-1,]
  return(matall.rtm)
  
})

cf1<- bind_cols(cf1.read,meta) %>% dplyr::select(-general_info)
colnames(cf1)<-c("ID_T1","Model","Database","Project","PY_ID","Date")






for(i in 1:nrow(cf1)){
  
  cf.temp<-cf1[i,]
  
  outdir.py<-paste(outdir,cf.temp$Database,cf.temp$Project,cf.temp$PY_ID,sep="/")
  
  lines<-str_detect(cost.tabs$ID_to,"id_t[:digit:]") %>% which
  cost.tabs.used<-cost.tabs %>% slice(lines)
  
  lists<-costs<-list()
  for(j in 1:nrow(cost.tabs.used)){
    
    is<-cost.tabs.used[j,]
    cf2.read<-dbGetQuery(con,statement=paste("select * from",is$Table,"where",is$ID_to,"=",unique(cf.temp$ID_T1))) %>% as.tibble
    cf2.read<-costfun.spectros(cf2.read)
    cf2.read<-costfun.param_user(cf2.read)
    cf2.read<-costfun.lut(cf2.read)
    
    costs[[j]]<-cf2.read
  }
  
  names(costs)<-cost.tabs.used$Table
}

cf2.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[2])) %>% as.tibble
cf2<-.sqljoin(cf1,cf2.read)
cf3.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[3])) %>% as.tibble
cf3<-.sqljoin(cf2,cf3.read)
cf4.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[4])) %>% as.tibble
cf4<-.sqljoin(cf3,cf4.read)
cf5.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[5])) %>% as.tibble
cf5<-.sqljoin(cf4,cf5.read)
cf6.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[6])) %>% as.tibble
cf6<-.sqljoin(cf5,cf6.read)
cf7.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[7])) %>% as.tibble
cf7<-.sqljoin(cf6,cf7.read)
cf8.read<-dbGetQuery(con,statement=paste("select * from",tables.srt$Table[8])) %>% as.tibble
cf8<-.sqljoin(cf7,cf8.read)


# for(i in 1:nrow(cf1)){
#   
#   cf.temp<-cf1[i,]
#   
#   lines<-str_detect(cost.tabs$ID_to,"id_t[:digit:]") %>% which
#   cost.tabs.used<-cost.tabs %>% slice(lines)
#   
#   #nrow(cost.tabs.used)
#   for(j in 1:5){
#     
#     if(j==1) to<-cf.temp
#     is<-cost.tabs.used[j,]
#     
#     cf2.read<-dbGetQuery(con,statement=paste("select * from",is$Table,"where",is$ID_to,"=",unique(to$ID_T1))) %>% as.tibble
#     to<-.sqljoin(to,cf2.read)
#     
#   }
# }





# cf1<-cf1.read %>% 
#   mutate(Info=map(general_info,function(x){
#     
#     matall<-readMat(x)$data[,,1]
#     matall.rtm<-matall$rtm[,,1] %>% 
#       melt %>% 
#       select(Type=L1,Value=value)
#     
#   })) %>% select(-general_info)
# 
# # Construct the PY_ID later linked to the File Structure
# cf1.id<-cf1 %>% 
#   mutate(PY_ID=map_dbl(Info,function(x) {
#     
#     x %>% filter(Type=="id") %>% select(Value) %>% as.numeric
#     
#   }))
